const secret=document.getElementById('secret'),state=document.getElementById('state'),content=document.getElementById('admin-content');
secret.value=sessionStorage.getItem('mecky-admin')||'';
async function call(path,method='GET',body){const r=await fetch(path,{method,headers:{'content-type':'application/json','x-admin-secret':secret.value},body:body?JSON.stringify(body):undefined});if(!r.ok)throw new Error(r.status===401?'Secret stimmt nicht.':'Anfrage fehlgeschlagen ('+r.status+').');return r.json()}
function item(parent,lines,button){const div=document.createElement('div');div.className='admin-item';for(const line of lines){const p=document.createElement('p');p.textContent=line;div.append(p)}if(button)div.append(button);parent.append(div)}
async function refresh(){const [knowledge,gaps,analytics]=await Promise.all([call('/admin/knowledge'),call('/admin/gaps'),call('/admin/analytics')]);content.hidden=false;sessionStorage.setItem('mecky-admin',secret.value);state.textContent='Verbunden.';
  const k=document.getElementById('knowledge');k.replaceChildren();for(const x of knowledge.items){const b=document.createElement('button');b.textContent=x.active?'Deaktivieren':'Inaktiv';b.disabled=!x.active;b.onclick=async()=>{await call('/admin/knowledge/'+x.id,'DELETE');refresh()};item(k,[x.category+' · '+x.subject,x.value,(x.valid_from||'ab sofort')+' bis '+(x.valid_until||'unbefristet')],b)}if(!knowledge.items.length)k.textContent='Noch keine Chef-Informationen.';
  const g=document.getElementById('gaps');g.replaceChildren();for(const x of gaps.items.slice(0,15))item(g,[x.topic,'Anfragen: '+x.occurrences]);if(!gaps.items.length)g.textContent='Noch keine Wissenslücken.';
  const a=document.getElementById('analytics');a.replaceChildren();item(a,['Interaktionen: '+analytics.total]);for(const x of analytics.intents)item(a,[x.intent+' · '+x.count+' Fragen']);for(const x of analytics.negative_feedback)item(a,['👎 '+x.intent,x.comment||x.answer]);
}
document.getElementById('connect').onclick=()=>refresh().catch(e=>state.textContent=e.message);
document.getElementById('knowledge-form').onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));for(const key of ['valid_from','valid_until'])if(!data[key])data[key]=null;try{await call('/admin/knowledge','POST',data);e.target.reset();await refresh()}catch(err){state.textContent=err.message}};
